[servers]

"CentOS 1" ansible_host=192.168.1.36 ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_user=root ansible_password=james
"CentOS 2" ansible_host=192.168.1.26 ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_user=root ansible_password=james
"CentOS 3" ansible_host=192.168.1.30 ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_user=root ansible_password=james
"CentOS 4" ansible_host=192.168.1.31 ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_user=root ansible_password=james
"CentOS 5" ansible_host=192.168.1.32 ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_user=root ansible_password=james



