version: '3.5'

networks:
  db-comparison-network:
    driver: bridge
    
services:

  # Zookeeper Service 1
  zookeeper1:
    image: bitnami/zookeeper
    container_name: zookeeper1
    hostname: zookeeper1
    restart: unless-stopped
    environment:
      ZOO_SERVER_ID: "1"
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_TICK_TIME: "2000"
      ZOO_SYNC_LIMIT: "2"
      ZOO_SERVERS: "0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
    networks:
      - db-comparison-network
    ports:
      - "2181:2181"
    volumes:
      - 'zoo1_data:/data'
  
  # Zookeeper Service 2
  zookeeper2:
    image: bitnami/zookeeper
    container_name: zookeeper2
    hostname: zookeeper2
    restart: unless-stopped
    environment:
      ZOO_SERVER_ID: "2"
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_TICK_TIME: "2000"
      ZOO_SYNC_LIMIT: "2"
      ZOO_SERVERS: "zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888"
    networks:
      - db-comparison-network
    ports:
      - "2182:2181"
    volumes:
      - 'zoo2_data:/data'
  
  # Zookeeper Service 3
  zookeeper3:
    image: bitnami/zookeeper
    container_name: zookeeper3
    hostname: zookeeper3
    restart: unless-stopped
    environment:
      ZOO_SERVER_ID: "3"
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_TICK_TIME: "2000"
      ZOO_SYNC_LIMIT: "2"
      ZOO_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888"
    networks:
      - db-comparison-network
    ports:
      - "2183:2181"
    volumes:
      - 'zoo3_data:/data'
  
  # Kafka Service
  kafka1:
    image: bitnami/kafka
    container_name: kafka1
    restart: unless-stopped
    ports:
      - "9091:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - db-comparison-network
    depends_on:
        - zookeeper1
        - zookeeper2
        - zookeeper3

  kafka2:
    image: bitnami/kafka
    container_name: kafka2
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper2:2182"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - db-comparison-network
    depends_on:
        - zookeeper1
        - zookeeper2
        - zookeeper3

  kafka3:
    image: bitnami/kafka
    container_name: kafka3
    restart: unless-stopped
    ports:
      - "9093:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper3:2183"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - db-comparison-network
    depends_on:
        - zookeeper1
        - zookeeper2
        - zookeeper3

volumes:
  zoo1_data:
  zoo2_data:
  zoo3_data: